In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Data Prep

In [ ]:
data = pd.read_csv('/content/drive/Shareddrives/Capstone AIRBUS/Data/msn_37_fuel_leak_signals_preprocessed.csv', delimiter=';')

In [ ]:
data

,UTC_TIME,FUEL_USED_2,FUEL_USED_3,FUEL_USED_4,FW_GEO_ALTITUDE,VALUE_FOB,VALUE_FUEL_QTY_CT,VALUE_FUEL_QTY_FT1,VALUE_FUEL_QTY_FT2,VALUE_FUEL_QTY_FT3,VALUE_FUEL_QTY_FT4,VALUE_FUEL_QTY_LXT,VALUE_FUEL_QTY_RXT,FLIGHT_PHASE_COUNT,FUEL_USED_1,Flight,MSN
0,2016-07-27 13:31:37,NaN,NaN,NaN,36.0,19862.0,0.0,1928.0,2710.0,2560.0,1921.0,5405.0,5339.0,2.0,NaN,0.0,F-RBAJ
1,2016-07-27 13:31:38,NaN,NaN,NaN,38.0,19862.0,0.0,1928.0,2710.0,2560.0,1921.0,5405.0,5339.0,2.0,NaN,0.0,F-RBAJ
2,2016-07-27 13:31:39,NaN,NaN,NaN,38.0,19862.0,0.0,1928.0,2710.0,2561.0,1921.0,5406.0,5338.0,2.0,NaN,0.0,F-RBAJ
3,2016-07-27 13:31:40,NaN,NaN,NaN,35.0,19862.0,0.0,1928.0,2709.0,2561.0,1921.0,5405.0,5339.0,2.0,NaN,0.0,F-RBAJ
4,2016-07-27 13:31:41,NaN,NaN,NaN,36.0,19862.0,0.0,1928.0,2710.0,2561.0,1922.0,5405.0,5339.0,2.0,NaN,0.0,F-RBAJ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3236640,2018-04-01 14:12:24,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7656.176758,497.0,F-RBAJ
3236641,2018-04-01 14:12:25,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7656.176758,497.0,F-RBAJ
3236642,2018-04-01 14:12:26,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7656.176758,497.0,F-RBAJ
3236643,2018-04-01 14:12:27,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7656.176758,497.0,F-RBAJ
3236644,2018-04-01 14:12:28,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7656.176758,497.0,F-RBAJ

In [ ]:
data.drop(data[(data["FLIGHT_PHASE_COUNT"] == 1) | (data["FLIGHT_PHASE_COUNT"] == 2) | (data["FLIGHT_PHASE_COUNT"] == 12)].index, inplace=True)

In [ ]:
numerical_columns = [
 'VALUE_FOB',
 'VALUE_FUEL_QTY_CT',
 'VALUE_FUEL_QTY_FT1',
 'VALUE_FUEL_QTY_FT2',
 'VALUE_FUEL_QTY_FT3',
 'VALUE_FUEL_QTY_FT4',
 'VALUE_FUEL_QTY_LXT',
 'VALUE_FUEL_QTY_RXT',]

In [ ]:
for column in numerical_columns:
    new_column_name = 'Dx_' + column
    data[new_column_name] = data[column].diff()

data

,UTC_TIME,FUEL_USED_2,FUEL_USED_3,FUEL_USED_4,FW_GEO_ALTITUDE,VALUE_FOB,VALUE_FUEL_QTY_CT,VALUE_FUEL_QTY_FT1,VALUE_FUEL_QTY_FT2,VALUE_FUEL_QTY_FT3,...,Flight,MSN,Dx_VALUE_FOB,Dx_VALUE_FUEL_QTY_CT,Dx_VALUE_FUEL_QTY_FT1,Dx_VALUE_FUEL_QTY_FT2,Dx_VALUE_FUEL_QTY_FT3,Dx_VALUE_FUEL_QTY_FT4,Dx_VALUE_FUEL_QTY_LXT,Dx_VALUE_FUEL_QTY_RXT
621,2016-07-27 13:41:58,NaN,NaN,NaN,66.0,19574.0,0.0,1857.0,2647.0,2476.0,...,0.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
622,2016-07-27 13:41:59,NaN,NaN,NaN,68.0,19606.0,0.0,1856.0,2644.0,2474.0,...,0.0,F-RBAJ,32.0,0.0,-1.0,-3.0,-2.0,-2.0,20.0,19.0
623,2016-07-27 13:42:00,NaN,NaN,NaN,72.0,19671.0,0.0,1856.0,2642.0,2473.0,...,0.0,F-RBAJ,65.0,0.0,0.0,-2.0,-1.0,-1.0,33.0,36.0
624,2016-07-27 13:42:01,NaN,NaN,NaN,73.0,19671.0,0.0,1856.0,2642.0,2473.0,...,0.0,F-RBAJ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
625,2016-07-27 13:42:02,NaN,NaN,NaN,76.0,19671.0,0.0,1856.0,2642.0,2473.0,...,0.0,F-RBAJ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3236640,2018-04-01 14:12:24,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,...,497.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3236641,2018-04-01 14:12:25,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,...,497.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3236642,2018-04-01 14:12:26,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,...,497.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3236643,2018-04-01 14:12:27,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,...,497.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3236644,2018-04-01 14:12:28,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,...,497.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
flight282 = data[data["Flight"] == 282]

flight282

,UTC_TIME,FUEL_USED_2,FUEL_USED_3,FUEL_USED_4,FW_GEO_ALTITUDE,VALUE_FOB,VALUE_FUEL_QTY_CT,VALUE_FUEL_QTY_FT1,VALUE_FUEL_QTY_FT2,VALUE_FUEL_QTY_FT3,...,Flight,MSN,Dx_VALUE_FOB,Dx_VALUE_FUEL_QTY_CT,Dx_VALUE_FUEL_QTY_FT1,Dx_VALUE_FUEL_QTY_FT2,Dx_VALUE_FUEL_QTY_FT3,Dx_VALUE_FUEL_QTY_FT4,Dx_VALUE_FUEL_QTY_LXT,Dx_VALUE_FUEL_QTY_RXT
1817902,2017-04-28 09:11:01,NaN,NaN,NaN,148.0,43581.0,9915.0,1840.0,2541.0,2672.0,...,282.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1817903,2017-04-28 09:11:02,NaN,NaN,NaN,152.0,43561.0,9913.0,1836.0,2539.0,2670.0,...,282.0,F-RBAJ,-20.0,-2.0,-4.0,-2.0,-2.0,-2.0,-5.0,-7.0
1817904,2017-04-28 09:11:03,NaN,NaN,NaN,157.0,43551.0,9913.0,1835.0,2538.0,2668.0,...,282.0,F-RBAJ,-10.0,0.0,-1.0,-1.0,-2.0,0.0,-1.0,-5.0
1817905,2017-04-28 09:11:04,NaN,NaN,NaN,161.0,43548.0,9913.0,1835.0,2538.0,2667.0,...,282.0,F-RBAJ,-3.0,0.0,0.0,0.0,-1.0,0.0,0.0,-1.0
1817906,2017-04-28 09:11:05,NaN,NaN,NaN,161.0,43548.0,9913.0,1835.0,2538.0,2667.0,...,282.0,F-RBAJ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1844477,2017-04-28 16:34:37,8130.049805,8293.357422,8224.420898,NaN,NaN,NaN,NaN,NaN,NaN,...,282.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1844478,2017-04-28 16:34:38,8130.049805,8293.357422,8224.420898,NaN,NaN,NaN,NaN,NaN,NaN,...,282.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1844479,2017-04-28 16:34:39,8130.049805,8293.357422,8224.420898,NaN,NaN,NaN,NaN,NaN,NaN,...,282.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1844480,2017-04-28 16:34:40,8130.049805,8293.357422,8224.420898,NaN,NaN,NaN,NaN,NaN,NaN,...,282.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1844481,2017-04-28 16:34:41,8130.049805,8293.357422,8224.420898,NaN,NaN,NaN,NaN,NaN,NaN,...,282.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
flight282["Dx_VALUE_FOB"].mean()

-1.2224744608399547

In [ ]:
data["Dx_VALUE_FOB"].mean()

-1.1294128026195982

In [ ]:
hgdata = data.drop(['UTC_TIME','MSN','FUEL_USED_1','FUEL_USED_2','FUEL_USED_3','FUEL_USED_4'], axis=1)
data.dropna(inplace=True)

In [ ]:
data = data.reset_index(drop=True)

data

,UTC_TIME,FUEL_USED_2,FUEL_USED_3,FUEL_USED_4,FW_GEO_ALTITUDE,VALUE_FOB,VALUE_FUEL_QTY_CT,VALUE_FUEL_QTY_FT1,VALUE_FUEL_QTY_FT2,VALUE_FUEL_QTY_FT3,...,Flight,MSN,Dx_VALUE_FOB,Dx_VALUE_FUEL_QTY_CT,Dx_VALUE_FUEL_QTY_FT1,Dx_VALUE_FUEL_QTY_FT2,Dx_VALUE_FUEL_QTY_FT3,Dx_VALUE_FUEL_QTY_FT4,Dx_VALUE_FUEL_QTY_LXT,Dx_VALUE_FUEL_QTY_RXT
0,2016-07-27 13:41:58,NaN,NaN,NaN,66.0,19574.0,0.0,1857.0,2647.0,2476.0,...,0.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-07-27 13:41:59,NaN,NaN,NaN,68.0,19606.0,0.0,1856.0,2644.0,2474.0,...,0.0,F-RBAJ,32.0,0.0,-1.0,-3.0,-2.0,-2.0,20.0,19.0
2,2016-07-27 13:42:00,NaN,NaN,NaN,72.0,19671.0,0.0,1856.0,2642.0,2473.0,...,0.0,F-RBAJ,65.0,0.0,0.0,-2.0,-1.0,-1.0,33.0,36.0
3,2016-07-27 13:42:01,NaN,NaN,NaN,73.0,19671.0,0.0,1856.0,2642.0,2473.0,...,0.0,F-RBAJ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2016-07-27 13:42:02,NaN,NaN,NaN,76.0,19671.0,0.0,1856.0,2642.0,2473.0,...,0.0,F-RBAJ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2917376,2018-04-01 14:12:24,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,...,497.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2917377,2018-04-01 14:12:25,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,...,497.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2917378,2018-04-01 14:12:26,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,...,497.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2917379,2018-04-01 14:12:27,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,...,497.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2917380,2018-04-01 14:12:28,7672.937988,7812.444336,7739.743652,NaN,NaN,NaN,NaN,NaN,NaN,...,497.0,F-RBAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.loc[1820186:1820283]

,UTC_TIME,FUEL_USED_2,FUEL_USED_3,FUEL_USED_4,FW_GEO_ALTITUDE,VALUE_FOB,VALUE_FUEL_QTY_CT,VALUE_FUEL_QTY_FT1,VALUE_FUEL_QTY_FT2,VALUE_FUEL_QTY_FT3,...,Flight,MSN,Dx_VALUE_FOB,Dx_VALUE_FUEL_QTY_CT,Dx_VALUE_FUEL_QTY_FT1,Dx_VALUE_FUEL_QTY_FT2,Dx_VALUE_FUEL_QTY_FT3,Dx_VALUE_FUEL_QTY_FT4,Dx_VALUE_FUEL_QTY_LXT,Dx_VALUE_FUEL_QTY_RXT
1820186,2017-04-28 09:49:05,NaN,NaN,NaN,28990.0,37525.0,6638.0,1875.0,2623.0,2635.0,...,282.0,F-RBAJ,153.0,-5.0,0.0,0.0,0.0,0.0,3.0,161.0
1820187,2017-04-28 09:49:06,NaN,NaN,NaN,28990.0,37668.0,6634.0,1875.0,2622.0,2634.0,...,282.0,F-RBAJ,143.0,-4.0,0.0,-1.0,-1.0,0.0,2.0,152.0
1820188,2017-04-28 09:49:07,NaN,NaN,NaN,28988.0,37803.0,6629.0,1874.0,2622.0,2633.0,...,282.0,F-RBAJ,135.0,-5.0,-1.0,0.0,-1.0,-1.0,3.0,142.0
1820189,2017-04-28 09:49:08,NaN,NaN,NaN,28990.0,37928.0,6624.0,1874.0,2622.0,2633.0,...,282.0,F-RBAJ,125.0,-5.0,0.0,0.0,0.0,0.0,1.0,135.0
1820190,2017-04-28 09:49:09,NaN,NaN,NaN,28989.0,38048.0,6619.0,1874.0,2621.0,2632.0,...,282.0,F-RBAJ,120.0,-5.0,0.0,-1.0,-1.0,0.0,1.0,127.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1820279,2017-04-28 09:50:38,NaN,NaN,NaN,28986.0,39497.0,6344.0,1846.0,2595.0,2594.0,...,282.0,F-RBAJ,25.0,-2.0,0.0,0.0,0.0,0.0,-1.0,28.0
1820280,2017-04-28 09:50:39,NaN,NaN,NaN,28986.0,39516.0,6341.0,1845.0,2594.0,2594.0,...,282.0,F-RBAJ,19.0,-3.0,-1.0,-1.0,0.0,2.0,-3.0,27.0
1820281,2017-04-28 09:50:40,NaN,NaN,NaN,28988.0,39536.0,6339.0,1844.0,2593.0,2594.0,...,282.0,F-RBAJ,20.0,-2.0,-1.0,-1.0,0.0,1.0,-1.0,25.0
1820282,2017-04-28 09:50:41,NaN,NaN,NaN,28989.0,39554.0,6336.0,1843.0,2592.0,2595.0,...,282.0,F-RBAJ,18.0,-3.0,-1.0,-1.0,1.0,1.0,-1.0,23.0
1820283,2017-04-28 09:50:42,NaN,NaN,NaN,28989.0,39571.0,6334.0,1842.0,2591.0,2595.0,...,282.0,F-RBAJ,17.0,-2.0,-1.0,-1.0,0.0,2.0,-1.0,22.0

In [ ]:
data.loc[1820131]

UTC_TIME                 2017-04-28 09:48:10
FUEL_USED_2                              NaN
FUEL_USED_3                              NaN
FUEL_USED_4                              NaN
FW_GEO_ALTITUDE                      28990.0
VALUE_FOB                            38254.0
VALUE_FUEL_QTY_CT                     6905.0
VALUE_FUEL_QTY_FT1                    1894.0
VALUE_FUEL_QTY_FT2                    2641.0
VALUE_FUEL_QTY_FT3                    2651.0
VALUE_FUEL_QTY_FT4                    1797.0
VALUE_FUEL_QTY_LXT                   12142.0
VALUE_FUEL_QTY_RXT                   10168.0
FLIGHT_PHASE_COUNT                       8.0
FUEL_USED_1                              NaN
Flight                                 282.0
MSN                                   F-RBAJ
Dx_VALUE_FOB                           112.0
Dx_VALUE_FUEL_QTY_CT                    -4.0
Dx_VALUE_FUEL_QTY_FT1                   -1.0
Dx_VALUE_FUEL_QTY_FT2                    0.0
Dx_VALUE_FUEL_QTY_FT3                    0.0
Dx_VALUE_FUEL_QTY_FT4                    0.0
Dx_VALUE_FUEL_QTY_LXT                    1.0
Dx_VALUE_FUEL_QTY_RXT                  121.0
Name: 1820131, dtype: object

In [ ]:
data['Dx_VALUE_FOB'].mean()

-1.1294128026195982

In [ ]:
data['Dx_VALUE_FUEL_QTY_FT3'].mean()

-0.010997085749423671

In [ ]:
data['TOTAL_CONSUMED'] = data['Dx_VALUE_FUEL_QTY_CT'] + data['Dx_VALUE_FUEL_QTY_FT1'] + data['Dx_VALUE_FUEL_QTY_FT2'] + data['Dx_VALUE_FUEL_QTY_FT3'] + data['Dx_VALUE_FUEL_QTY_FT4'] + data['Dx_VALUE_FUEL_QTY_LXT'] + data['Dx_VALUE_FUEL_QTY_RXT']

In [ ]:
data['TOTAL_CONSUMED'].mean()

-1.1294512285803988

In [ ]:
# Group by 'Flight' and calculate the average number of rows
avg_rows = data.groupby('Flight').size().mean()

# Display the average number of rows for each flight
print(avg_rows)

9387.125412541254

# Reduced Dataset

Creating a reduced Dataset with the derivative values of Fuel on Board, Total Consumption (aggregation of the 7 fuel quantity columns) and Flight number

In [ ]:
df_reduced = data[['Dx_VALUE_FOB', 'TOTAL_CONSUMED', 'Flight']]

In [ ]:
df_reduced

         Dx_VALUE_FOB  TOTAL_CONSUMED  Flight
1087              9.0            -3.0     0.0
1088              8.0            15.0     0.0
1089              0.0             0.0     0.0
1090              0.0             0.0     0.0
1091              0.0             0.0     0.0
...               ...             ...     ...
4455828           0.0            -1.0  2023.0
4455829          -1.0            -1.0  2023.0
4455830          -1.0             1.0  2023.0
4455831          -2.0            -5.0  2023.0
4455832          -1.0             1.0  2023.0

[3712809 rows x 3 columns]

In [ ]:
df_reduced['Dx_VALUE_FOB'].mean()

-1.0419029976118244

In [ ]:
# Number of unique flights
df_reduced['Flight'].nunique()

334

In [ ]:
# Mean derivative value of FOB for the dataset
mean_fob = df_reduced['Dx_VALUE_FOB'].mean()
# Mean derivative value of Total Consumption for the dataset
mean_consumed = df_reduced['TOTAL_CONSUMED'].mean()
flight = 2025

y = 300   # Number of rows with a varying value
x = 11116 - y  # Number of rows to add
z = 50   # Multiplier for varying value

new_rows = []
varying_group = []

for i in range(x):
    row = [mean_fob, mean_consumed, flight]  # Initializing with constant values
    if i < y:
        row[0] = row[0] * z  # Setting varying value as z times the constant value
        row[1] = row[1] * z
        varying_group.append(row)
    new_rows.append(row)

# Find the position where the varying group should be inserted
insert_index = len(new_rows) - x//2

leak_flight = new_rows[:insert_index] + varying_group + new_rows[insert_index:]

leak_flight_df = pd.DataFrame(leak_flight, columns=['Dx_VALUE_FOB', 'TOTAL_CONSUMED', 'Flight'])

synthetic_reduced = pd.concat([df_reduced, leak_flight_df], axis=0)

synthetic_reduced = synthetic_reduced.reset_index(drop=True)

synthetic_reduced.iloc[3718224]

Dx_VALUE_FOB       -52.095150
TOTAL_CONSUMED     -52.097159
Flight            2025.000000
Name: 3718224, dtype: float64

In [ ]:
leak_flight_df[5407:5709]

      Dx_VALUE_FOB  TOTAL_CONSUMED  Flight
5407     -1.041903       -1.041943    2025
5408    -52.095150      -52.097159    2025
5409    -52.095150      -52.097159    2025
5410    -52.095150      -52.097159    2025
5411    -52.095150      -52.097159    2025
...            ...             ...     ...
5704    -52.095150      -52.097159    2025
5705    -52.095150      -52.097159    2025
5706    -52.095150      -52.097159    2025
5707    -52.095150      -52.097159    2025
5708     -1.041903       -1.041943    2025

[302 rows x 3 columns]

In [ ]:
leak_flight_df

       Dx_VALUE_FOB  TOTAL_CONSUMED  Flight
0        -52.095150      -52.097159    2025
1        -52.095150      -52.097159    2025
2        -52.095150      -52.097159    2025
3        -52.095150      -52.097159    2025
4        -52.095150      -52.097159    2025
...             ...             ...     ...
11111     -1.041903       -1.041943    2025
11112     -1.041903       -1.041943    2025
11113     -1.041903       -1.041943    2025
11114     -1.041903       -1.041943    2025
11115     -1.041903       -1.041943    2025

[11116 rows x 3 columns]

In [ ]:
insert_index

5408

In [ ]:
!mkdir -p '/content/drive/MyDrive/path/to/save'

In [ ]:
synthetic_reduced.to_csv('/content/drive/MyDrive/path/to/save/synthetic_reduced.csv', index=False)

In [ ]:
synthetic_reduced[3718216:3718518]

         Dx_VALUE_FOB  TOTAL_CONSUMED  Flight
3718216     -1.041903       -1.041943  2025.0
3718217    -52.095150      -52.097159  2025.0
3718218    -52.095150      -52.097159  2025.0
3718219    -52.095150      -52.097159  2025.0
3718220    -52.095150      -52.097159  2025.0
...               ...             ...     ...
3718513    -52.095150      -52.097159  2025.0
3718514    -52.095150      -52.097159  2025.0
3718515    -52.095150      -52.097159  2025.0
3718516    -52.095150      -52.097159  2025.0
3718517     -1.041903       -1.041943  2025.0

[302 rows x 3 columns]

In [ ]:
synthetic_reduced

         Dx_VALUE_FOB  TOTAL_CONSUMED  Flight
0            9.000000       -3.000000     0.0
1            8.000000       15.000000     0.0
2            0.000000        0.000000     0.0
3            0.000000        0.000000     0.0
4            0.000000        0.000000     0.0
...               ...             ...     ...
3723920     -1.041903       -1.041943  2025.0
3723921     -1.041903       -1.041943  2025.0
3723922     -1.041903       -1.041943  2025.0
3723923     -1.041903       -1.041943  2025.0
3723924     -1.041903       -1.041943  2025.0

[3723925 rows x 3 columns]

# Regular Dataset

In [ ]:
df_regular = data[['Dx_VALUE_FOB', 'Dx_VALUE_FUEL_QTY_CT', 'Dx_VALUE_FUEL_QTY_FT1', 'Dx_VALUE_FUEL_QTY_FT2', 'Dx_VALUE_FUEL_QTY_FT3', 'Dx_VALUE_FUEL_QTY_FT4', 'Dx_VALUE_FUEL_QTY_LXT', 'Dx_VALUE_FUEL_QTY_RXT', 'Flight']]

df_regular

,Dx_VALUE_FOB,Dx_VALUE_FUEL_QTY_CT,Dx_VALUE_FUEL_QTY_FT1,Dx_VALUE_FUEL_QTY_FT2,Dx_VALUE_FUEL_QTY_FT3,Dx_VALUE_FUEL_QTY_FT4,Dx_VALUE_FUEL_QTY_LXT,Dx_VALUE_FUEL_QTY_RXT,Flight
1087,9.0,0.0,2.0,-2.0,0.0,-4.0,10.0,-9.0,0.0
1088,8.0,0.0,0.0,0.0,1.0,6.0,12.0,-4.0,0.0
1089,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1090,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
4455828,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,2023.0
4455829,-1.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,2023.0
4455830,-1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2023.0
4455831,-2.0,0.0,-1.0,-1.0,-2.0,0.0,-1.0,0.0,2023.0
4455832,-1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2023.0

In [ ]:
# Mean values for each column
mean_values = {}

for column in df_regular.columns:
    mean_values[f"mean_{column}"] = df_regular[column].mean()

# Accessing the mean values for each column
for column, mean in mean_values.items():
    print(f"Mean value for column '{column}': {mean}")

Mean value for column 'mean_Dx_VALUE_FOB': -1.0419029976118244
Mean value for column 'mean_Dx_VALUE_FUEL_QTY_CT': -0.15771643518425
Mean value for column 'mean_Dx_VALUE_FUEL_QTY_FT1': -0.0038057438451587463
Mean value for column 'mean_Dx_VALUE_FUEL_QTY_FT2': -0.007563814890558604
Mean value for column 'mean_Dx_VALUE_FUEL_QTY_FT3': -0.008481987627157767
Mean value for column 'mean_Dx_VALUE_FUEL_QTY_FT4': -0.004962549918404098
Mean value for column 'mean_Dx_VALUE_FUEL_QTY_LXT': -0.43383378999566097
Mean value for column 'mean_Dx_VALUE_FUEL_QTY_RXT': -0.42557885417752433
Mean value for column 'mean_Flight': 1236.0817696251006

In [ ]:
mean_values

{'mean_Dx_VALUE_FOB': -1.0419029976118244,
 'mean_Dx_VALUE_FUEL_QTY_CT': -0.15771643518425,
 'mean_Dx_VALUE_FUEL_QTY_FT1': -0.0038057438451587463,
 'mean_Dx_VALUE_FUEL_QTY_FT2': -0.007563814890558604,
 'mean_Dx_VALUE_FUEL_QTY_FT3': -0.008481987627157767,
 'mean_Dx_VALUE_FUEL_QTY_FT4': -0.004962549918404098,
 'mean_Dx_VALUE_FUEL_QTY_LXT': -0.43383378999566097,
 'mean_Dx_VALUE_FUEL_QTY_RXT': -0.42557885417752433,
 'mean_Flight': 1236.0817696251006}

In [ ]:
# Mean values for each column
mean_values = {}

for column in df_regular.columns:
    mean_values[f"mean_{column}"] = df_regular[column].mean()

y = 30   # Number of rows with a varying value
x = 11116 - y  # Number of rows to add
z = 5   # Multiplier for varying value
flight = 2026

new_rows = []
varying_group = []

for i in range(x):
    row = [mean_values['mean_Dx_VALUE_FOB'], mean_values['mean_Dx_VALUE_FUEL_QTY_CT'], mean_values['mean_Dx_VALUE_FUEL_QTY_FT1'], mean_values['mean_Dx_VALUE_FUEL_QTY_FT2'],mean_values['mean_Dx_VALUE_FUEL_QTY_FT3'], mean_values['mean_Dx_VALUE_FUEL_QTY_FT4'], mean_values['mean_Dx_VALUE_FUEL_QTY_LXT'], mean_values['mean_Dx_VALUE_FUEL_QTY_RXT'], flight]  # Initializing with constant values
    if i < y:
      for n in range(8):
        row[n] = row[n] * z  # Setting varying value as z times the constant value
        varying_group.append(row)
    new_rows.append(row)

# Find the position where the varying group should be inserted
insert_index = len(new_rows) - x//2

leak_flight = new_rows[:insert_index] + varying_group + new_rows[insert_index:]

leak_flight_df = pd.DataFrame(leak_flight, columns=['Dx_VALUE_FOB',	'Dx_VALUE_FUEL_QTY_CT',	'Dx_VALUE_FUEL_QTY_FT1',	'Dx_VALUE_FUEL_QTY_FT2',	'Dx_VALUE_FUEL_QTY_FT3',	'Dx_VALUE_FUEL_QTY_FT4',	'Dx_VALUE_FUEL_QTY_LXT',	'Dx_VALUE_FUEL_QTY_RXT',	'Flight'])

synthetic = pd.concat([df_regular, leak_flight_df], axis=0)

synthetic = synthetic.reset_index(drop=True)

synthetic

,Dx_VALUE_FOB,Dx_VALUE_FUEL_QTY_CT,Dx_VALUE_FUEL_QTY_FT1,Dx_VALUE_FUEL_QTY_FT2,Dx_VALUE_FUEL_QTY_FT3,Dx_VALUE_FUEL_QTY_FT4,Dx_VALUE_FUEL_QTY_LXT,Dx_VALUE_FUEL_QTY_RXT,Flight
0,9.000000,0.000000,2.000000,-2.000000,0.000000,-4.000000,10.000000,-9.000000,0.0
1,8.000000,0.000000,0.000000,0.000000,1.000000,6.000000,12.000000,-4.000000,0.0
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...
3724130,-1.041903,-0.157716,-0.003806,-0.007564,-0.008482,-0.004963,-0.433834,-0.425579,2026.0
3724131,-1.041903,-0.157716,-0.003806,-0.007564,-0.008482,-0.004963,-0.433834,-0.425579,2026.0
3724132,-1.041903,-0.157716,-0.003806,-0.007564,-0.008482,-0.004963,-0.433834,-0.425579,2026.0
3724133,-1.041903,-0.157716,-0.003806,-0.007564,-0.008482,-0.004963,-0.433834,-0.425579,2026.0
3724134,-1.041903,-0.157716,-0.003806,-0.007564,-0.008482,-0.004963,-0.433834,-0.425579,2026.0

In [ ]:
synthetic[3718216:3718518]

,Dx_VALUE_FOB,Dx_VALUE_FUEL_QTY_CT,Dx_VALUE_FUEL_QTY_FT1,Dx_VALUE_FUEL_QTY_FT2,Dx_VALUE_FUEL_QTY_FT3,Dx_VALUE_FUEL_QTY_FT4,Dx_VALUE_FUEL_QTY_LXT,Dx_VALUE_FUEL_QTY_RXT,Flight
3718216,-1.041903,-0.157716,-0.003806,-0.007564,-0.008482,-0.004963,-0.433834,-0.425579,2026.0
3718217,-1.041903,-0.157716,-0.003806,-0.007564,-0.008482,-0.004963,-0.433834,-0.425579,2026.0
3718218,-1.041903,-0.157716,-0.003806,-0.007564,-0.008482,-0.004963,-0.433834,-0.425579,2026.0
3718219,-1.041903,-0.157716,-0.003806,-0.007564,-0.008482,-0.004963,-0.433834,-0.425579,2026.0
3718220,-1.041903,-0.157716,-0.003806,-0.007564,-0.008482,-0.004963,-0.433834,-0.425579,2026.0
...,...,...,...,...,...,...,...,...,...
3718513,-5.209515,-0.788582,-0.019029,-0.037819,-0.042410,-0.024813,-2.169169,-2.127894,2026.0
3718514,-5.209515,-0.788582,-0.019029,-0.037819,-0.042410,-0.024813,-2.169169,-2.127894,2026.0
3718515,-5.209515,-0.788582,-0.019029,-0.037819,-0.042410,-0.024813,-2.169169,-2.127894,2026.0
3718516,-5.209515,-0.788582,-0.019029,-0.037819,-0.042410,-0.024813,-2.169169,-2.127894,2026.0
3718517,-5.209515,-0.788582,-0.019029,-0.037819,-0.042410,-0.024813,-2.169169,-2.127894,2026.0

In [ ]:
synthetic.to_csv('/content/drive/MyDrive/path/to/save/synthetic.csv', index=False)

# New Version

In [ ]:
df_synthetic = data[['Dx_VALUE_FOB', 'Dx_VALUE_FUEL_QTY_CT', 'Dx_VALUE_FUEL_QTY_FT1', 'Dx_VALUE_FUEL_QTY_FT2', 'Dx_VALUE_FUEL_QTY_FT3', 'Dx_VALUE_FUEL_QTY_FT4', 'Dx_VALUE_FUEL_QTY_LXT', 'Dx_VALUE_FUEL_QTY_RXT']]

df_synthetic = df_synthetic.reset_index(drop=True)

df_synthetic

,Dx_VALUE_FOB,Dx_VALUE_FUEL_QTY_CT,Dx_VALUE_FUEL_QTY_FT1,Dx_VALUE_FUEL_QTY_FT2,Dx_VALUE_FUEL_QTY_FT3,Dx_VALUE_FUEL_QTY_FT4,Dx_VALUE_FUEL_QTY_LXT,Dx_VALUE_FUEL_QTY_RXT
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,32.0,0.0,-1.0,-3.0,-2.0,-2.0,20.0,19.0
2,65.0,0.0,0.0,-2.0,-1.0,-1.0,33.0,36.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2917376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2917377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2917378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2917379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2917380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_synthetic.iloc[125000:125011]

,Dx_VALUE_FOB,Dx_VALUE_FUEL_QTY_CT,Dx_VALUE_FUEL_QTY_FT1,Dx_VALUE_FUEL_QTY_FT2,Dx_VALUE_FUEL_QTY_FT3,Dx_VALUE_FUEL_QTY_FT4,Dx_VALUE_FUEL_QTY_LXT,Dx_VALUE_FUEL_QTY_RXT
125000,0.0,0.0,-1.0,3.0,-1.0,-1.0,-4.0,4.0
125001,-3.0,0.0,-1.0,2.0,0.0,0.0,-7.0,2.0
125002,-7.0,0.0,-2.0,2.0,1.0,0.0,-6.0,0.0
125003,-1.0,0.0,0.0,2.0,-1.0,0.0,-5.0,1.0
125004,-4.0,0.0,0.0,4.0,-2.0,-1.0,-3.0,1.0
125005,3.0,0.0,0.0,3.0,-1.0,-2.0,-1.0,2.0
125006,4.0,0.0,0.0,4.0,-1.0,0.0,-2.0,3.0
125007,-1.0,0.0,0.0,2.0,0.0,-1.0,-5.0,3.0
125008,-2.0,0.0,-1.0,3.0,-1.0,-1.0,-5.0,2.0
125009,0.0,0.0,1.0,4.0,-1.0,-1.0,-3.0,0.0
125010,1.0,0.0,0.0,4.0,-1.0,-1.0,-2.0,1.0

In [ ]:
# Duplicating already existing anomalies

df_synthetic.iloc[2000000:2000043] = df_synthetic.iloc[1825350:1825393]

In [ ]:
# Replicating the structure of anomalies found in hte regular dataset

rows_to_modify = range(125000, 125025)  # Indexes of the 25 rows to modify

i = 0

for row_index in rows_to_modify:
    # Add 20 to the 'FOB' column
    if i < 10:

      df_synthetic.loc[row_index, 'Dx_VALUE_FOB'] += 20
      df_synthetic.loc[row_index, 'Dx_VALUE_FUEL_QTY_FT2'] += 20

    else:

      df_synthetic.loc[row_index, 'Dx_VALUE_FOB'] -= 20
      df_synthetic.loc[row_index, 'Dx_VALUE_FUEL_QTY_FT2'] -= 20

    i = i + 1

In [ ]:
df_synthetic.iloc[125000:125025]

,Dx_VALUE_FOB,Dx_VALUE_FUEL_QTY_CT,Dx_VALUE_FUEL_QTY_FT1,Dx_VALUE_FUEL_QTY_FT2,Dx_VALUE_FUEL_QTY_FT3,Dx_VALUE_FUEL_QTY_FT4,Dx_VALUE_FUEL_QTY_LXT,Dx_VALUE_FUEL_QTY_RXT
125000,40.0,0.0,-1.0,43.0,-1.0,-1.0,-4.0,4.0
125001,37.0,0.0,-1.0,42.0,0.0,0.0,-7.0,2.0
125002,33.0,0.0,-2.0,42.0,1.0,0.0,-6.0,0.0
125003,39.0,0.0,0.0,42.0,-1.0,0.0,-5.0,1.0
125004,36.0,0.0,0.0,44.0,-2.0,-1.0,-3.0,1.0
125005,43.0,0.0,0.0,43.0,-1.0,-2.0,-1.0,2.0
125006,44.0,0.0,0.0,44.0,-1.0,0.0,-2.0,3.0
125007,39.0,0.0,0.0,42.0,0.0,-1.0,-5.0,3.0
125008,38.0,0.0,-1.0,43.0,-1.0,-1.0,-5.0,2.0
125009,40.0,0.0,1.0,44.0,-1.0,-1.0,-3.0,0.0
125010,-39.0,0.0,0.0,-36.0,-1.0,-1.0,-2.0,1.0
125011,-39.0,0.0,0.0,-37.0,0.0,-1.0,-2.0,3.0
125012,-39.0,0.0,-1.0,-37.0,-1.0,0.0,-2.0,2.0
125013,-38.0,0.0,1.0,-37.0,0.0,-1.0,-2.0,2.0
125014,-37.0,0.0,-1.0,-37.0,-1.0,0.0,0.0,1.0
125015,-35.0,0.0,0.0,-37.0,0.0,0.0,-1.0,1.0
125016,-38.0,0.0,0.0,-37.0,0.0,0.0,-2.0,2.0
125017,-38.0,0.0,0.0,-37.0,0.0,0.0,-2.0,2.0
125018,-40.0,0.0,0.0,-38.0,0.0,0.0,-2.0,-1.0
125019,-37.0,0.0,-1.0,-37.0,0.0,1.0,1.0,-1.0
125020,-38.0,0.0,1.0,-37.0,-1.0,-1.0,0.0,0.0
125021,-38.0,0.0,-1.0,-37.0,0.0,0.0,0.0,0.0
125022,-39.0,0.0,0.0,-37.0,0.0,0.0,0.0,0.0
125023,-35.0,0.0,0.0,-38.0,-1.0,0.0,0.0,2.0
125024,-37.0,0.0,0.0,-37.0,0.0,-1.0,-1.0,2.0

In [ ]:
df_synthetic.to_csv('/content/drive/MyDrive/path/to/save/synthetic_FOB_FT2.csv', index=False)